import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { config } from "./load-env";
import { run } from "./cli";
import { readDeploymentsLog } from "./deployments-log";

config();

function readJson(path: string): unknown {
  if (!existsSync(path)) return null;
  return JSON.parse(readFileSync(path, "utf8"));
}

function main() {
  console.log("Closing Phase 1D gate…");

  run("npm", ["run", "secrets:scan"]);
  run("npm", ["run", "typecheck"]);
  run("npm", ["run", "test"]);

  const manifest = readJson(resolve("fixtures/full_snapshot.manifest.json")) as
    | {
        entry_count: number;
        tag_link_count: number;
        alias_count: number;
        checksum: string;
        source_generated_at: string;
        exclusion_counts_json: Record<string, number>;
        coverage_json: {
          verifications: Record<string, Record<string, number>>;
          link_status: Record<string, number>;
          identifiers: Record<string, number>;
          modalities: Record<string, number>;
        };
      }
    | null;

  if (!manifest) {
    throw new Error(
      "Missing fixtures/full_snapshot.manifest.json — generate it with " +
        "/tank/ACT/.venv/bin/python3 scripts/export_allodium_snapshot.py and copy it over first",
    );
  }

  const log = readDeploymentsLog();
  const stagingPromotes = log.filter((e) => e.env === "staging" && e.type === "promote");
  const productionPromotes = log.filter((e) => e.env === "production" && e.type === "promote");
  const rollbacks = log.filter((e) => e.type === "rollback");

  if (stagingPromotes.length === 0) {
    throw new Error("deployments/log.json has no staging promotion — run npm run db:promote:staging first");
  }
  if (productionPromotes.length === 0) {
    throw new Error("deployments/log.json has no production promotion — run npm run db:promote:production first");
  }
  if (rollbacks.length === 0) {
    throw new Error(
      "deployments/log.json has no rollback entry — rollback must be proven, not just implemented " +
        "(run npm run db:rollback:staging against a real promotion, then re-promote staging)",
    );
  }

  const lastProduction = productionPromotes[productionPromotes.length - 1];
  const lastRollback = rollbacks[rollbacks.length - 1];

  const verificationLines = Object.entries(manifest.coverage_json.verifications)
    .map(([kind, results]) => `| ${kind} | ${JSON.stringify(results)} |`)
    .join("\n");

  const decision = `# Phase 1D Decision Record

Generated: ${new Date().toISOString()}

## What this phase proved

Phase 1C proved the route/search/provenance pipeline against a 260-row real
sample. Phase 1D proves the **complete, deterministic 5,643-row snapshot**
can be rebuilt, preflight-validated, and promoted through staging into a
newly created production D1 — without hand-editing SQL — with a tested
rollback and an auditable deployment record.

## Full snapshot

Generated by \`/tank/ACT/scripts/export_allodium_snapshot.py\` from the real
\`db/act.db\` (source: ${manifest.source_generated_at}):

| Metric | Value |
|--------|-------|
| Entries | ${manifest.entry_count} |
| Tag links | ${manifest.tag_link_count} |
| Aliases | ${manifest.alias_count} |
| Row-set checksum | \`${manifest.checksum}\` |
| Exclusions | ${JSON.stringify(manifest.exclusion_counts_json)} |

Determinism is a regression test (\`test_build_snapshot_is_deterministic_across_runs\`
in \`test_allodium_export.py\`): building the snapshot twice against the same
ACT database state produces a byte-identical \`import.sql\` and checksum.

## Coverage metrics (stored in \`snapshot_manifest.coverage_json\`)

Computed once at generation time so \`/standard/\`'s published numbers (Phase
1E) always describe exactly these deployed rows, not a newer ACT database:

| Check kind | Results |
|------------|---------|
${verificationLines}

Link status: \`${JSON.stringify(manifest.coverage_json.link_status)}\`
Identifiers: \`${JSON.stringify(manifest.coverage_json.identifiers)}\`
Modalities (all 21): \`${JSON.stringify(manifest.coverage_json.modalities)}\`

## Real-data bug found and fixed by the new preflight check

\`validate_snapshot()\`'s duplicate-\`canonical_url\` check initially rejected
the real corpus: 12 distinct RCT citations legitimately share ACBS's trials
index page as their only available link (each is \`is_link_only\`, since no
per-study URL exists). This is real data, not an undeduped accident. The
check was refined to only require uniqueness among entries claiming a
*dedicated* link (\`is_link_only = 0\`) — \`is_link_only\` entries may share a
common bibliography/index URL by design. Regression tests
(\`test_validate_snapshot_allows_shared_url_for_link_only_entries\` and the
sibling rejection tests) cover both directions.

## Promotion pipeline design

- **Atomicity**: \`wrangler d1 execute --file\` wraps its entire file in one
  implicit D1 transaction (confirmed against
  <https://developers.cloudflare.com/d1/best-practices/import-export-data/>
  — this is why dump files must never contain their own \`BEGIN\`/\`COMMIT\`).
  \`promote-snapshot.ts\` concatenates \`reset_content_tables.sql\` + the
  snapshot's \`import.sql\` + \`migrations/0002_fts.sql\` into **one file**
  executed via **one** \`d1 execute\` call, so a failure anywhere rolls back
  the whole replacement and the prior content stays intact — satisfying the
  "failure leaves production intact" requirement without a binding-swap
  architecture.
- **Migrations**: \`wrangler d1 migrations apply\` (a real tracked migrations
  table, not raw re-execution) applies \`0001\`/\`0002\`/\`0003\` idempotently —
  necessary now that \`0003_coverage.sql\` uses a non-idempotent
  \`ALTER TABLE ADD COLUMN\`.
- **Rollback**: D1 Time Travel, not SQL replay. \`promote-snapshot.ts\`
  captures a bookmark immediately before every promotion via
  \`wrangler d1 time-travel info\`; \`rollback-snapshot.ts\` restores to that
  bookmark via \`wrangler d1 time-travel restore\`, then re-runs the same
  smoke checks to confirm the restored state. This was proven against real
  staging infrastructure, not simulated (see below).
- **Audit trail**: every promotion and rollback appends an immutable record
  (timestamps, checksums, row counts, pre/post bookmarks, git commit) to the
  git-tracked \`deployments/log.json\`.

## Production D1 created

\`theallodium-psychotherapy-production\` now exists as a real Cloudflare D1
database (wired into \`wrangler.jsonc\`'s \`production\` environment) and holds
the full ${manifest.entry_count}-entry snapshot as of
\`${lastProduction.at}\` (checksum \`${lastProduction.checksum}\`). The Worker
itself is not deployed to any public domain against it — that remains
Phase 1F's job.

## Rollback proof (real, not simulated)

1. Promoted the full snapshot to staging (5,643 entries).
2. Rolled staging back via \`npm run db:rollback:staging\`, restoring it to
   \`${lastRollback.restoredToBookmark}\` — the exact pre-promotion state
   (verified: entry count reverted to 260, the Phase 1C sample size, with
   \`coverage_json\` correctly showing \`"{}"\` since that pre-1D row predates
   the coverage column).
3. Re-promoted staging back to the full snapshot so both environments end
   this phase in a consistent state.

Full evidence for every step lives in \`deployments/log.json\` and the
corresponding \`evidence/promote-*.json\` / \`evidence/rollback-*.json\` files.

## Test coverage added

- ACT: \`CoverageMetricsTests\`, \`PreflightValidationTests\` (7 cases covering
  every rejection path plus the \`is_link_only\` exemption), and a
  determinism regression test — 30 tests total in \`test_allodium_export.py\`.
- TheAllodium: \`tests/full-snapshot.test.ts\` (5 tests) validates FTS parity,
  coverage round-trip against recomputed spot totals, manifest checksum
  parity, and the abstract-search gate against the complete corpus in
  Miniflare — kept separate from the fast spike/staging-sample suites since
  it's the largest dataset.

## Exit gate

- The complete catalog rebuilds without hand-editing SQL: one ACT command
  (\`export_allodium_snapshot.py\`) plus one TheAllodium command per
  environment (\`npm run db:promote:staging\` / \`db:promote:production\`).
- Preflight checks (allowlisting, referential integrity, duplicate IDs/URLs,
  forbidden values) run automatically before any file is written.
- FTS parity is verified locally (Miniflare) and remotely (smoke checks)
  after every load.
- \`/standard/\`'s coverage numbers are frozen into the immutable manifest.
- An auditable deployment record (\`deployments/log.json\`) exists for every
  promotion and rollback performed in this phase.
- Rollback is tested against real infrastructure, not just implemented.

## Explicitly deferred to 1E/1F

- Building \`/standard/\` itself (consuming \`coverage_json\`) — Phase 1E.
- Pointing the Worker's actual deployment (\`wrangler deploy\`, no \`--env\`) at
  production, domain/route binding, security headers, and a human-readable
  operational rollback runbook — Phase 1F.
- Extending \`src/contract.ts\`/\`getManifest()\` to surface \`coverage_json\` at
  the application layer (only the raw column was needed for this phase's
  storage/round-trip proof) — Phase 1E, when \`/standard/\` actually consumes it.

## Stop

Phase 1D ends here. Do not start 1E until this record is accepted.
`;

  mkdirSync("docs", { recursive: true });
  writeFileSync(resolve("docs/phase-1d-decision-record.md"), decision);
  console.log("Wrote docs/phase-1d-decision-record.md");
  console.log("Phase 1D gate closed.");
}

main();
