import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { config } from "./load-env";
import { run } from "./cli";

config();

function readJson(path: string): unknown {
  if (!existsSync(path)) return null;
  return JSON.parse(readFileSync(path, "utf8"));
}

function main() {
  console.log("Closing Phase 1C gate…");

  run("npm", ["run", "secrets:scan"]);
  run("npm", ["run", "typecheck"]);
  run("npm", ["run", "test"]);

  const sampleManifest = readJson(resolve("fixtures/staging_sample.manifest.json")) as
    | {
        entry_count: number;
        tag_link_count: number;
        alias_count: number;
        checksum: string;
        source_generated_at: string;
        exclusion_counts_json: Record<string, number>;
      }
    | null;
  const stagingSmoke = readJson(resolve("evidence/staging-sample-smoke.json"));

  if (!sampleManifest) {
    throw new Error(
      "Missing fixtures/staging_sample.manifest.json — copy it from ACT's " +
        "exports/allodium/psychotherapy/staging-sample-*/ directory first",
    );
  }
  if (!stagingSmoke) {
    throw new Error(
      "Missing evidence/staging-sample-smoke.json — run npm run db:load:staging-sample && npm run db:smoke:staging-sample first",
    );
  }

  const decision = `# Phase 1C Decision Record

Generated: ${new Date().toISOString()}

## What this phase proved

Phase 1A proved the Hono/D1/FTS mechanics against a 12-row **synthetic**
fixture. Phase 1C proves the same route/search/provenance code paths against
a **real, ACT-sourced representative sample** — no new Worker code was
required, since \`src/index.tsx\`, \`src/db/repository.ts\`, and
\`src/views/pages.tsx\` already implemented everything this phase needed to
validate.

## Sample composition

Generated by \`/tank/ACT/scripts/export_allodium_staging_sample.py\` from the
real \`db/act.db\` (source: ${sampleManifest.source_generated_at}):

| Metric | Value |
|--------|-------|
| Entries | ${sampleManifest.entry_count} (of 5,643 public-safe) |
| Tag links | ${sampleManifest.tag_link_count} |
| Aliases | ${sampleManifest.alias_count} |
| Row-set checksum | \`${sampleManifest.checksum}\` |

Coverage guarantees enforced by \`select_representative_sample()\`: every
real alias whose canonical is public-safe, a sample of blocked-link entries,
a sample of entries missing author/published_date, a sample of DOI-bearing
entries, and at least 3 entries per therapy modality (all 21 modalities
present in the real corpus are represented).

## Real-data bug found and fixed

Loading the real sample surfaced two defects the 12-row synthetic fixture
never could:

1. **Semicolons inside real title strings** broke the naive
   line/semicolon-based SQL statement splitter used by the Workers-pool test
   fixture loader. Fixed by rewriting \`tests/sql-test-utils.ts\`'s
   \`splitSql()\` to be string-literal-aware (tracks single-quoted string
   state, handles \`''\`-escaped quotes, only treats \`;\`/\`--\`/\`/* */\` as
   syntax outside a string).
2. **D1's 100,000-byte maximum SQL statement length** (confirmed against
   <https://developers.cloudflare.com/d1/platform/limits/>, enforced
   identically by workerd locally and D1 remotely) was violated by
   \`export_allodium_snapshot.py\`'s fixed 500-row \`SQL_CHUNK_SIZE\`, which
   never accounted for serialized byte size. Fixed by rewriting
   \`_emit_insert()\` to chunk by a conservative 80,000-byte budget instead
   of row count, with a regression test
   (\`SqlStatementSizeTests\` in \`test_allodium_export.py\`) that fails if any
   future statement exceeds the budget. This also protects Phase 1D's much
   larger full-corpus import.

Both fixes were verified against a real remote D1 load (not just the local
Miniflare test pool) via \`npm run db:load:staging-sample\`.

## Test coverage added

\`tests/staging-sample.test.ts\` (9 tests, Workers-compatible vitest pool)
discovers its assertion subjects by querying the loaded real data rather
than hardcoding IDs, so it stays valid across sample regenerations:

- Manifest reflects a bounded sample, not the full corpus; abstract search
  gate is off.
- \`entry_fts\` row count matches \`entries\` row count after rebuild.
- No \`abstract_text\` leaks into \`entry_search_documents\` while the gate is
  off.
- A real alias resolves via 301 to its canonical, which renders without
  forbidden fields or the synthetic-fixture-era XSS/leak regressions.
- A real blocked-link entry renders "link inconclusive" and remains
  discoverable via search.
- A real entry missing bibliographic fields renders placeholders without
  crashing.
- FTS keyword search ranks and paginates correctly against real title/tag
  distributions; \`LIKE\` fallback returns parity results.

\`scripts/test_allodium_staging_sample.py\` (7 tests, ACT side) covers the
sampler's coverage guarantees, determinism given a fixed seed, and that
\`build_snapshot()\` output stays scoped to only the sampled entries.

## Remote staging evidence

\`\`\`json
${JSON.stringify(stagingSmoke, null, 2)}
\`\`\`

## Exit gate

- One ACT command creates the artifact: \`.venv/bin/python3 scripts/export_allodium_staging_sample.py\`
- One documented operation loads staging: \`npm run db:load:staging-sample\`
- Route/search integration tests pass in a Workers-compatible test environment: \`npm test\` (25/25 passing, including the 9 real-data tests above)

## Explicitly deferred to 1D

- The full 5,643-row deterministic snapshot pipeline (this phase used a
  260-row representative subset by design)
- Preflight checks for referential integrity, duplicate IDs/URLs, and
  forbidden values at full-corpus scale
- Storing \`/standard/\` coverage metrics inside the snapshot
- Staging→production promotion and rollback runbook

## Stop

Phase 1C ends here. Do not start 1D until this record is accepted.
`;

  mkdirSync("docs", { recursive: true });
  writeFileSync(resolve("docs/phase-1c-decision-record.md"), decision);
  console.log("Wrote docs/phase-1c-decision-record.md");
  console.log("Phase 1C gate closed.");
}

main();
